name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Clone CoolProp source
        uses: actions/checkout@v4
        with:
          repository: CoolProp/CoolProp
          path: CoolProp
          submodules: recursive
          # Pin to the version vendored in twine-models 0.2.2.
          ref: 98b3523d5daa98454618d381d2ae53f7471d216b

      - name: Set up cache
        uses: Swatinem/rust-cache@v2

      - name: Check formatting
        run: cargo fmt --check

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features -- -W clippy::pedantic -D warnings
        env:
          COOLPROP_SOURCE_DIR: ${{ github.workspace }}/CoolProp

      - name: Run tests
        run: cargo test --all-features
        env:
          COOLPROP_SOURCE_DIR: ${{ github.workspace }}/CoolProp
